version: '3'

services:
  mysqldb:
    container_name: mysqldesafio
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ~/mysql:/var/lib/mysql
    network_mode: host